# Generated by Django 2.2.7 on 2019-12-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_heatmode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heatmode',
            table='HeatMode',
        ),
    ]
