# Generated by Django 2.2.7 on 2019-12-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20191204_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeatMode',
        ),
        migrations.AddField(
            model_name='activity',
            name='min_heat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='purchase_change',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='scan_change',
            field=models.FloatField(default=0.02),
        ),
        migrations.AddField(
            model_name='activity',
            name='star_change',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='heat',
            field=models.FloatField(default=50.0),
        ),
    ]
