# Generated by Django 2.2.4 on 2019-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
