# Generated by Django 2.2.4 on 2019-12-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_ticket_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
