# Generated by Django 2.2.7 on 2020-01-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20191223_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inspector_apply_list',
            field=models.ManyToManyField(related_name='inspector_apply_list', to='test_app.Activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='inspector_list',
            field=models.ManyToManyField(related_name='inspector_list', to='test_app.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='starred',
            field=models.ManyToManyField(related_name='starred', to='test_app.Activity'),
        ),
    ]
