# Generated by Django 2.2.4 on 2019-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(default=3, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
