# Generated by Django 2.2.7 on 2019-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='heat',
            field=models.FloatField(default=0.0),
        ),
    ]
