# Generated by Django 2.2.4 on 2019-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='heat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='remain',
            field=models.IntegerField(default=100),
        ),
    ]
