# Generated by Django 2.2.4 on 2019-11-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20191119_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(default='无', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(default='0000.00.00 00:00', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.Activity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.User'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
