# Generated by Django 2.2.7 on 2019-11-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20191124_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(default='none place', max_length=30),
        ),
    ]
