# Generated by Django 2.2.7 on 2019-11-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191126_1008'),
        ('test_app', '0006_auto_20191126_1519'),
    ]

    operations = [
    ]
