# Generated by Django 2.2.7 on 2019-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191205_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='QRCode',
            field=models.ImageField(default='QR/default.png', upload_to='QR'),
        ),
    ]
