# Generated by Django 2.2.7 on 2019-11-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_merge_20191127_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='media/test_image.jpg', upload_to='images'),
        ),
    ]
