# Generated by Django 2.2.7 on 2019-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='default/test_image.jpg', upload_to='images'),
        ),
    ]
