# Generated by Django 2.2.7 on 2019-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20191128_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='哎呀，这个活动的介绍文字似乎走丢了...', max_length=1024),
        ),
    ]
