# Generated by Django 2.2.7 on 2019-11-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='publisher',
            field=models.CharField(default='unknown publisher', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchaseTime',
            field=models.DateTimeField(default='2018-09-04 14:55:55', verbose_name='购票日期'),
        ),
    ]
