# Generated by Django 2.2.7 on 2019-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20191128_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchaseTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='购票日期'),
        ),
    ]
