# Generated by Django 2.2.7 on 2019-11-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_auto_20191128_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default='2019-10-10 12:30:00'),
        ),
    ]
