# Generated by Django 2.2.7 on 2019-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20191128_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='正在抢票', max_length=20),
        ),
    ]
